config:
  build_stage: /gpfs/alpine/proj-shared/csc303/pnorbert/spack-stage/

  # Cache directory for miscellaneous files, like the package index.
  # This can be purged with `spack clean --misc-cache`
  misc_cache: $spack/misc_cache
